### ISSUE TITLE
an option to pass read_timeout for rates updates

### ISSUE THREAD

**Issue by starbeast** [RubyMoney/eu_central_bank#100]
Time taken by `update_rates` call depends on response time of the European Central Bank servers and it's only possible to interrupt using `Timeout::timeout` (which can cause bugs) if the call is stuck in case I'd like to use a fallback bank. That would be great if I could pass timeout option to this call so it will be used by the underlying `open` call

**Comment by antstorm** [comment]
Sounds like a great idea, would you be up for opening a PR to add this?
