### ISSUE TITLE
No rates available for ARS

### ISSUE THREAD

**Issue by sajjadmurtaza** [RubyMoney/eu_central_bank#105]
`
Money.new(5, "ARS").exchange_to('EUR').to_f
`

> CurrencyUnavailable: No rates available for ARS

Is there any fix for this in future?

**Comment by antstorm** [comment]
This gem is using EU Central Bank's exchange rates, which are limited to these currencies — https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml.

Consider using other gems that provide exchange rates for a broader range of currencies — https://github.com/RubyMoney/money#implementations

**Comment by joshuapinter** [comment]
It would be nice to override the rates for unsupported currencies manually, with something like: 

```ruby
config.add_rates( "USD", "ARS", 1.2345 )
```

That's how it's shown in the RubyMoney README: 

![image](https://user-images.githubusercontent.com/180819/108738661-1a2c8e00-74f1-11eb-90d3-f5311381c926.png)
