### ISSUE TITLE
Calling `update_rates` without a cache file on a `puma` cluster pins CPU threads to 100%.

### ISSUE THREAD

**Issue by joshuapinter** [RubyMoney/eu_central_bank#112]
Prior to setting up a cache file to store the latest currency exchange rates and just have them updated on a daily basis, we were just doing `update_rates` on our `money.rb` initializer. 

After the first request, all of the `puma` workers (that were called) became pinned at 100% CPU usage so this is what our development machine's `htop` looked like _at idle_ after the first few requests: 

![image](https://user-images.githubusercontent.com/180819/108094804-7187b580-703c-11eb-832f-4e4a409115a4.png)

I went down a rabbit hole with `puma`, thinking it must be the culprit, but it was actually just calling `update_rates` that caused this. Here is a comparison of what changes between this issue being present or not. 

## Issue Present

```ruby
eu_central_bank = EuCentralBank.new

eu_central_bank.update_rates

config.default_bank = eu_central_bank
```

## Issue _NOT_ Present

```ruby
eu_central_bank = EuCentralBank.new

eu_central_bank.update_rates( Rails.root.join( "rates.xml" ) )

config.default_bank = eu_central_bank
```

We've moved on by just using a cache file but I wanted to post this here because I searched and I didn't find any Issues documenting this.

**Comment by semmons99** [comment]
@joshuapinter can you check if https://github.com/RubyMoney/eu_central_bank/pull/110 solves your issue?

**Comment by joshuapinter** [comment]
@semmons99 You bet. I'll try and take a look this weekend.

**Comment by joshuapinter** [comment]
Sorry for the delay. I'll take a look this week to confirm.

**Comment by joshuapinter** [comment]
To confirm, I upgraded to 1.7.0 and don't run into the issue, so I think it is now resolved. Thanks for handling and happy holidays! 🎄

**Comment by semmons99** [comment]
great. thank you!
