### ISSUE TITLE
RUB is missing from exchange rates

### ISSUE THREAD

**Issue by trafium** [RubyMoney/eu_central_bank#118]
As of today, we started to get errors about missing exchange rate for EUR-RUB (Russian Ruble). 

`> Money.default_bank.update_rates`
```
=> #<EuCentralBank:0x00007fb8fa3c3d80 @store=#<Money::RatesStore::StoreWithHistoricalDataSupport:0x00007fb8fa3c3d58 @rates={"EUR_TO_USD"=>0.11076e1, "EUR_TO_JPY"=>0.12818e3, "EUR_TO_BGN"=>0.19558e1, "EUR_TO_CZK"=>0.25634e2, "EUR_TO_DKK"=>0.74399e1, "EUR_TO_GBP"=>0.82773e0, "EUR_TO_HUF"=>0.37864e3, "EUR_TO_PLN"=>0.47691e1, "EUR_TO_RON"=>0.49496e1, "EUR_TO_SEK"=>0.107688e2, "EUR_TO_CHF"=>0.10192e1, "EUR_TO_ISK"=>0.1434e3, "EUR_TO_NOK"=>0.98418e1, "EUR_TO_HRK"=>0.757e1, "EUR_TO_TRY"=>0.156897e2, "EUR_TO_AUD"=>0.15139e1, "EUR_TO_BRL"=>0.56041e1, "EUR_TO_CAD"=>0.13992e1, "EUR_TO_CNY"=>0.69996e1, "EUR_TO_HKD"=>0.86547e1, "EUR_TO_IDR"=>0.1593442e5, "EUR_TO_ILS"=>0.35872e1, "EUR_TO_INR"=>0.84174e2, "EUR_TO_KRW"=>0.13342e4, "EUR_TO_MXN"=>0.228945e2, "EUR_TO_MYR"=>0.4637e1, "EUR_TO_NZD"=>0.16329e1, "EUR_TO_PHP"=>0.57293e2, "EUR_TO_SGD"=>0.15042e1, "EUR_TO_THB"=>0.36063e2, "EUR_TO_ZAR"=>0.168798e2, "EUR_TO_EUR"=>1}, @options={}, @guard=#<Monitor:0x00007fb8fa3c3ce0 @mon_mutex=#<Thread::Mutex:0x00007fb8fa3c3c18>, @mon_mutex_owner_object_id=70216224480880, @mon_owner=nil, @mon_count=0>>, @rounding_method=nil, @currency_string=nil, @rates_updated_at=2022-03-03 00:00:00 +0200, @last_updated=2022-03-04 13:57:02 +0200>
```

**Comment by ahukkanen** [comment]
https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

> Owing to current trading activity in the EUR/RUB market, the European Central Bank (ECB) is not in a position to set a reference rate that is representative of prevailing market conditions. The ECB has therefore decided to suspend its publication of a euro reference rate for the Russian rouble until further notice. The ECB last published a [EUR/RUB reference rate](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-rub.en.html) on 1 March 2022.

This means that for the time being, ECB has removed these rates from their APIs as well.

**Comment by trafium** [comment]
@ahukkanen 
Thank you for the info!
