### ISSUE TITLE
Uncaught exception: Net::ReadTimeout

### ISSUE THREAD

**Issue by netwire88** [RubyMoney/eu_central_bank#121]
All of a sudden, we are gettin `Uncaught exception: Net::ReadTimeout`, did the project go down?

**Comment by Splitrox** [comment]
Same thing here

**Comment by netwire88** [comment]
It looks like https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml is down

**Comment by Splitrox** [comment]
Maybe there's some way to make sure this gem doesn't crash the whole site?

**Comment by netwire88** [comment]
Until there's a better solution, you can do this
1. Download latest [eurofxref-daily.txt](https://github.com/RubyMoney/eu_central_bank/files/9077691/eurofxref-daily.txt) and rename extension to `.xml` (can't upload XML files to GitHub)
2. Add it to your `/config/initializers` or somewhere similar
3. In `money.rb`, replace `config.default_bank.update_rates` with `config.default_bank.update_rates(Rails.root.join('config', 'initializers', 'eurofxref-daily.xml'))`

At least that'll start your project. I tried the code below in `money.rb` but the timeout is really long, so it doesn't work

```
  begin
    config.default_bank.update_rates
  rescue
    config.default_bank.update_rates(Rails.root.join('config', 'initializers', 'eurofxref-daily.xml'))
  end
```

**Comment by dobreandl** [comment]
https://github.com/rmustafin/russian_central_bank This also works if you're looking for a quick fix

**Comment by dobreandl** [comment]
https://github.com/rmustafin/russian_central_bank - This also works, if you're looking for a quick fix.

**Comment by ephraimm** [comment]
The feed is not down there has been a CAPTCHA check added:

Security Check
Our systems have detected unusual traffic from your computer network. 
This page checks to see if it is really you sending the requests and not a bot.

Please click [here](https://www.ecb.europa.eu/myracloud-captcha/?q=%2Fstats%2Feurofxref%2Feurofxref-daily.xml%3Faa47d0a7203affb68fcfd620dfd072a8) to verify that you are not a bot.

**Comment by bjer** [comment]
Any alternative sources? Don't really trust a Russian bank.. Could download https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml with curl after filling in the captcha but 
the eu_central_bank gem fails to do so.

**Comment by ephraimm** [comment]
try https://github.com/spk/money-open-exchange-rates
