### ISSUE TITLE
TypeError: nil can't be coerced into Fixnum

### ISSUE THREAD

**Issue by DmitryKK** [RubyMoney/eu_central_bank#36]
I have following code:
```
bank = EuCentralBank.new
bank.add_rate(:EUR, :USD, 10)
Money.default_bank = bank
Money.new(100, :EUR).exchange_to(:USD)
```

And i get

```
TypeError: nil can't be coerced into Fixnum
from /Users/dmitrij/.rvm/gems/ruby-2.2.2@my_app/gems/eu_central_bank-0.5.0/lib/eu_central_bank.rb:57:in `/'
```
Apparently rate is set to nil, but:
```
bank.get_rate(:EUR, :USD)
=> 10
Money.default_bank.get_rate(:EUR, :USD)
=> 10
```
What could be the problem?

Thanks in advance.

**Comment by semmons99** [comment]
This gem is unique in that it needs to know how both the `from` and `to` of a rate conversion relate to `:EUR`, so if you do `bank.add_rate(:EUR, :EUR, 1)` everything would work. But more importantly, why are you defining your own rates and not just calling `bank.update_rates`?

**Comment by DmitryKK** [comment]
Ok, thank you very much. It's working perfect! It is necessary to run tests, because `Real HTTP connections are disabled` in test env

Counter question. Can I bypass euro relation and add a custom rate for example from USD to CAD?

**Comment by semmons99** [comment]
If you're using the eu_central_bank gem, no. Can you use the VCR gem in your test env to record the update_rates call once and then use it in future tests?

**Comment by DmitryKK** [comment]
I'll try. Thanks for the advice!
