### ISSUE TITLE
nil can't be coerced into Float

### ISSUE THREAD

**Issue by santa-nika** [RubyMoney/eu_central_bank#42]
Hi there, 

when trying to exchange:

     Money.add_rate("EUR", "USD", 0.123)
     Money.new(100, 'EUR').exchange_to("USD")

I get

     TypeError:
           nil can't be coerced into Float
            # .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eu_central_bank-0.5.0/lib/eu_central_bank.rb:64:in `/'
            # .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eu_central_bank-0.5.0/lib/eu_central_bank.rb:64:in `exchange_with'
            # .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/money-6.5.1/lib/money/money.rb:412:in `exchange_to'

I already found the reason for this..
dirty fix: also add 

     Money.add_rate("EUR", "EUR", 1)

but I would like to contribute a clean patch for this issue.
**Question: how to fork the current version 0.5.0, because I can only clone version 0.4.0 here via github?**

Thx!

**Comment by semmons99** [comment]
I'm not sure what happened. 0.5.0 was the Jan 9 commit. Just clone from master to patch it.

**Comment by takiy33** [comment]
I add 0.5.0 tag on Jan 9 commit.

**Comment by santa-nika** [comment]
@takiy33 but not here? https://github.com/RubyMoney/eu_central_bank/blob/master/eu_central_bank.gemspec#L5

**Comment by takiy33** [comment]
@santa-nika I also think that it is strange.
