### ISSUE TITLE
undefined method `synchronize' for nil:NilClass

### ISSUE THREAD

**Issue by cavebring** [RubyMoney/eu_central_bank#45]
If I try to `update_rates` I get this error.

    NoMethodError: undefined method `synchronize' for nil:NilClass
    from /.rvm/gems/ruby-2.3.0/gems/eu_central_bank-0.3.8/lib/eu_central_bank.rb:69:in `update_parsed_rates`

Just me or broken master?

`Rails 4.2.5`
`ruby 2.3.0p0`

**Comment by ahukkanen** [comment]
Same here.

**Comment by ahukkanen** [comment]
Probably the reason is here:
https://github.com/RubyMoney/money/commit/6bf21596e9073551ab774e92450bd83cc935491f

The @mutex variable is no longer available in the parent class.

**Comment by hafizio** [comment]
Same here

**Comment by ahukkanen** [comment]
#46 should fix this issue.

In the meanwhile (while waiting for the update), you can try to pull the fixes directly from GitHub by adding this to your Gemfile:

```ruby
gem 'eu_central_bank', git: 'https://github.com/mainio/eu_central_bank.git', branch: 'fix/money_recent'
```

Please note that as mentioned in #46, the historical exchange rates are not currently supported, so if you are using those, do not use that version of the gem.

Let me know if you notice any problems! I have only run it against the test set contained in the repo but it might not cover everything (although it covers a lot).

**Comment by schorsch** [comment]
using mainio branch, which makes my specs pass. So it seems to work.

**Comment by ahukkanen** [comment]
Also a sidenote that that version has been also been updated to support the historical rates, so there shouldn't be any problems running that against your existing code base anymore, even if you're using those.

The build is only failing for jruby-19 and the remaining issue relates to thread safety under that ruby. Others seem to pass fine but if you're using jruby, you should probably wait until that gets resolved.

**Comment by unabl4** [comment]
Same here. Thanks for the fixed version

**Comment by ahukkanen** [comment]
Update to this:

The issues related to jruby should be also now fixed in the linked branch above. They were thread safety issues that possibly affected also other ruby versions, so updating is highly recommended if you're using the branch version.

Let's hope this gets solved in the official release as well with #46.

**Comment by markets** [comment]
Hi guys, thanks a lot for fixing this! any plan to push a new version to RubyGems? I'm using this as a dependency for another gem, and I can't point to GitHub repo via `gemspec`. So, for now I'm freezing to `0.5.0`...

cc/ @ahukkanen

**Comment by cavebring** [comment]
Any update on push to master for this fix?

**Comment by antstorm** [comment]
I will release a new version of the gem later today

**Comment by antstorm** [comment]
Version 1.0.1 is now available on RubyGems — https://rubygems.org/gems/eu_central_bank

I think this issue is now resolved, so I'm closing it. In case there's something left — feel free to open a new one.
