### ISSUE TITLE
"NoMethodError: undefined method `/' for nil:NilClass"  for certain currencies

### ISSUE THREAD

**Issue by peterb0yd** [RubyMoney/eu_central_bank#47]
Note: This error occurs with 145 of the 178 currencies available.

Money.new(100_00, 'GBP').exchange_to('BYR')
NoMethodError: undefined method `/' for nil:NilClass
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/eu_central_bank-d2cc9ac3c8f5/lib/eu_central_bank.rb:63:in `exchange_with'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/money-6.7.0/lib/money/money.rb:434:in `exchange_to'
	from (irb):294
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/peter/TipShield/workspace/tipshield/bin/rails:9:in `<top (required)>'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/peter/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):295:0>

**Comment by peterb0yd** [comment]
Ah, looking at the source code, it seems these are the only currencies available for conversion:

["USD", "JPY", "BGN", "CZK", "DKK", "GBP", "HUF", "ILS", "PLN", "RON", "SEK", "CHF", "NOK", "HRK", "RUB", "TRY", "AUD", "BRL", "CAD", "CNY", "HKD", "IDR", "INR", "KRW", "MXN", "MYR", "NZD", "PHP", "SGD", "THB", "ZAR"]

**Comment by peterb0yd** [comment]
This list seems to be the most common global currencies which works fine for my purposes. Thanks for the sweet gem. Closing.

**Comment by APiercey** [comment]
I've been running into this problem even with supported currencies:

```
Money.new(100, 'CAD').exchange_to('EUR')
NoMethodError: undefined method `/' for nil:NilClass
from /Users/alexanderpiercey/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eu_central_bank-1.0.1/lib/eu_central_bank.rb:63:in `exchange_with'
```

**Comment by antstorm** [comment]
@APiercey it seems like the error is caused by not being able to get a direct rate and falling back to a double exchange via EUR… can you try any other exchanges?

**Comment by APiercey** [comment]
Unfortunately, I get the same result.
```
Money.new(100, 'USD').exchange_to('EUR')
NoMethodError: undefined method `/' for nil:NilClass
from /Users/alexanderpiercey/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eu_central_bank-1.0.1/lib/eu_central_bank.rb:63:in `exchange_with'
```
```
Money.new(100, 'EUR').exchange_to('USD')
NoMethodError: undefined method `/' for nil:NilClass
from /Users/alexanderpiercey/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eu_central_bank-1.0.1/lib/eu_central_bank.rb:63:in `exchange_with'
```

However, `EUR` to `EUR` works fine, it seems.
```
Money.new(100, 'EUR').exchange_to('EUR')
=> #<Money fractional:100 currency:EUR>
```

**Comment by bbnnt** [comment]
it ends up working after some retries or firing some `eu_bank.update_rates`, but that feels unsafe.
Is that due to their api ?
