### ISSUE TITLE
No explicit error when rate is not defined.

### ISSUE THREAD

**Issue by lomefin** [RubyMoney/eu_central_bank#48]
I work with CLP (Chilean Peso)

I was trying to use rails-money gem and I wanted to test the exchange system. The EUBank is configured as default bank.

`Money.new(1000, "CLP").exchange_to("EUR")`

Returns 
```

TypeError: nil can't be coerced into Fixnum
from /.../gems/eu_central_bank-1.0.1/lib/eu_central_bank.rb:63:in `/'
```

There could be a check, so if the currency is not found a more specific error can be thrown, such as NonExistingCurrecyError or something.

**Comment by antstorm** [comment]
I guess since #49 is merged this is now fixed. Closing it.
