### ISSUE TITLE
exchange for a specific date

### ISSUE THREAD

**Issue by julioalucero** [RubyMoney/eu_central_bank#52]
Is not posible to exchange for a specific date?
I try:

```
require 'eu_central_bank'
eu_bank = EuCentralBank.new
Money.default_bank = eu_bank
money1 = Money.new(10)
money1.bank # eu_bank

eu_bank.update_rates

eu_bank.exchange(100, "CAD", "USD", Date.parse('2012-01-01')) # NoMethodError: undefined method `/' for nil:NilClass
```

I think that the problem is because the rates are not cache for a specific date, but is not posible to call `update_rates` with a date. 

So, it is an error or the feature does not exists?

**Comment by antstorm** [comment]
@julioalucero sorry for a delay, was busy. So it seems that there is a `update_historical_rates` method that will fetch 90 day rates, although not all of them are parsed correctly (will investigate that). But yeah, getting a 4 year old rate seems to not be a feature.

**Comment by bak1an** [comment]
@antstorm 

https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml 

That url seems to be returning almost 10 years of rates data, if you guys are interested I could open a pull request adding support for that.

**Comment by antstorm** [comment]
@bak1an we love PRs, please do open one with this feature 👍
