### ISSUE TITLE
Saving rates every day

### ISSUE THREAD

**Issue by ivanjolic95** [RubyMoney/eu_central_bank#53]
What's the best approach if I need to save rates into a file every day and use it while evaluating prices created at that date? Should I just save them into something like `exchange_rates/dd_mm_yyyy.xml` and then load the rates from the correct file based on when price was created or is there a better option? Is there a way to keep them all in one file and just ask the gem to give the rate for a given date? Thanks!

**Comment by antstorm** [comment]
@ivanjolic95 so currently there's no built-in mechanism for doing that, but you've got a couple of options there. First one is the one you've suggested — dump output into an XML and load it whenever necessary. But you can also use any other format instead (CSV or JSON) and load the values one by one using the `Money#add_rate` method.

In case you're working on an app with a DB connection you might wanna utilize that for better querying.

You can definitely use the built-in date filtering for that falling back to preloading rates from DB/file.
