### ISSUE TITLE
Nokogiri dependency throws deprecation warnings in Ruby 2.4.0

### ISSUE THREAD

**Issue by bovender** [RubyMoney/eu_central_bank#54]
The Gemspec requires Nokogiri:

    s.add_dependency "nokogiri", "~> 1.6.3"

Which triggers tons of deprecation warnings with Ruby 2.4.0 because of the [Fixnum/Bignum deprecation](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released).

It's fixed in Nokogiri 1.7.0 (sparklemotion/nokogiri#1564).

Is it possible to relax the dependency?

**Comment by antstorm** [comment]
@bovender sure, but it needs to be ruby version dependent, since Nokogiri 1.7 also dropped support for older rubies

**Comment by bovender** [comment]
Ah ok, sure. Unfortunately I'm unable to help with that -- don't know enough about Gemspec dependencies.

**Comment by antstorm** [comment]
No problem, I'll add this one

**Comment by bovender** [comment]
May I ask one more thing -- the ruby version-dependent dependency somehow does not work:

```sh
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    nokogiri (~> 1.7.0)

    eu_central_bank (~> 1.0) was resolved to 1.0.0, which depends on
      nokogiri (~> 1.6.3)
$ irb
irb(main):001:0> puts RUBY_VERSION
2.4.0
=> nil
irb(main):002:0> 
```

The `RUBY_VERSION` is 2.4.0, but the nokogiri dependency is not properly resolved.

Maybe this is not the right place to ask this, but maybe I'm just missing something simple.

**Comment by antstorm** [comment]
So it says that `eu_central_bank` got resolved to 1.0.0, which is an older version. You want `1.1.0` for ruby 2.4.0 support.

**Comment by bovender** [comment]
I really don't mean to be a nuisance, but the output is the same when I fix the version at 1.1.0 in the Gemfile. When I [download the gem](https://rubygems.org/downloads/eu_central_bank-1.1.0.gem) from RubyGems.org and extract the files, the `metadata` file contained in `metadata.gz` does not mention nokogiri 1.7.0:

        --- !ruby/object:Gem::Specification
        name: eu_central_bank
        version: !ruby/object:Gem::Version
          version: 1.1.0
        platform: ruby
        authors:
        - Shane Emmons
        autorequire: 
        bindir: bin
        cert_chain: []
        date: 2017-01-19 00:00:00.000000000 Z
        dependencies:
        - !ruby/object:Gem::Dependency
          name: nokogiri
          requirement: !ruby/object:Gem::Requirement
            requirements:
            - - ~>
              - !ruby/object:Gem::Version
                version: 1.6.3
          type: :runtime
          prerelease: false
          version_requirements: !ruby/object:Gem::Requirement
            requirements:
            - - ~>
              - !ruby/object:Gem::Version
                version: 1.6.3
          [...]

When I clone the repository and build the gem myself using Ruby 2.4.0, I find this inside the `metadata` file:

        --- !ruby/object:Gem::Specification
        name: eu_central_bank
        version: !ruby/object:Gem::Version
          version: 1.1.0
        platform: ruby
        authors:
        - Shane Emmons
        autorequire: 
        bindir: bin
        cert_chain: []
        date: 2017-01-25 00:00:00.000000000 Z
        dependencies:
        - !ruby/object:Gem::Dependency
          name: nokogiri
          requirement: !ruby/object:Gem::Requirement
            requirements:
            - - "~>"
              - !ruby/object:Gem::Version
                version: 1.7.0
          type: :runtime
          prerelease: false
          version_requirements: !ruby/object:Gem::Requirement
            requirements:
            - - "~>"
              - !ruby/object:Gem::Version
                version: 1.7.0
          [...]

Which makes me wonder if the `RUBY_VERSION` switch is really resolved at installation time, rather than packaging time.

**Comment by antstorm** [comment]
@bovender sounds like you're right… and a quick search revealed the fact that it might be impossible to achieve. So it seems like we need to relax the dependency on the gem (`'>= 1.6.3', '< 2.0'`), allowing devs to pick the right one in their Gemfiles.

**Comment by ahukkanen** [comment]
@antstorm Maybe just put it to readme that if you're using older Ruby < 2.4.0, use X version of this gem?

**Comment by antstorm** [comment]
@ahukkanen it would make sense to drop the support of Ruby <= 2.0, yes, since it's what causing most of the issues right now. I wonder how many people are still running older rubies…

**Comment by ahukkanen** [comment]
Yeah, that's true, too. I would guess not that many people.

**Comment by antstorm** [comment]
I guess it's time to do that :)
