### ISSUE TITLE
Problem getting exchange rates

### ISSUE THREAD

**Issue by pabse** [RubyMoney/eu_central_bank#58]
Hey there,

I tried to get the exchange rate from foreign_value to other foreign_value (or euros), but I always get `nil`. Getting rates from EUR to foreign_value works well.
Example: (default_bank is EuCentralBank)
```
Money.default_bank.get_rate('GBP', 'EUR')
=> nil

Money.default_bank.get_rate('EUR', 'GBP')
=> #<BigDecimal:7fe19819b190,'0.86595E0',9(18)>

Money.default_bank.get_rate('GBP', 'USD')
=> nil
```

The actual exchange works very well.

Did I miss something?
How can I get the exchange rates here? I need them so save the value in a `ExchangeEvent` record in my current application.

Regards,
pabse

**Comment by antstorm** [comment]
@pabse European Central Bank will only give exchange rates **from euros to other currencies**. If you need a more flexible solution try https://github.com/RubyMoney/google_currency. Although it also has it's limitations.

**Comment by pabse** [comment]
Ok, I understand that.

But the exchange works this way. I can do
```
Money.from_amount(5, 'USD').exchange_to('CHF')
```
And it gives me the correct result.
So the correct rates must be there.
Can we add this as a feature to `get_rate`?

**Comment by antstorm** [comment]
@pabse good point, so the correct rate aren't actually there, but what `eu_central_bank` does is it figures out the rate based on 2 other rates. So in your example it sees that there's no rate `USD -> CHF`, so it's trying to get `EUR -> USD` and `EUR -> CFH` and returns the rate based on these 2 divided. I'm not sure if that's the correct way to do it…

**Comment by pabse** [comment]
As I understand and check it correctly the rate is always `(eur_to_{to} / eur_to_{from})`.
Example:
```
1 CZK->JPY
> 1 * (EUR_TO_JPY / EUR_TO_CZK)
# Rates from 2017-01-23
> 1 * ( 121.72 / 27.027 )
> 4.503644503644503
```
Our friend Google says:  `4.4931089`.
So this should be ok. (some rounding errors here, but we can ignore that)
This also works for several other currencies.

So we could either add this rate calculation to the `get_rate` method or calculate the rates on a `update_rates` call and save it. For performance reasons it would be better so save it, but we have to save it in every possible way then. This means: `EUR_TO_USD`, `USD_TO_EUR`, `USD_TO_{every_other_currency}`, `{every_other_currency}_TO_USD`.

**Comment by antstorm** [comment]
While this trick works, it sounds like there's a potential for an incorrect result (0.01 in your example is still quite significant). So while it's a workaround it sounds to me like it should come with a flag confirming that you're fine with getting back potentially incorrect result.

**Comment by pabse** [comment]
As far as I see we have no other option than doing this, as we don't have the necessary information. The EU Central Bank only gives you this small set of exchange rates.
So it's basically no workaround. It's the only possible way.

But we could add a little warning in the README that one may get incorrect results if exchanging from non-euro to non-euro currency.

**Comment by antstorm** [comment]
@pabse well it's the limitation of the underlying API which developers will have to accept. It's definitely worth adding a README note and something like `perform_indirect_exchange` option that will try and do double conversion.

**Comment by zachaysan** [comment]
I agree that this is necessary.

For now I'm just monkey patching my own method on, but I can share the code if required. Also, we should add a section for a recommended rails model / migration so that we're all not re-inventing the wheel. If you guys want I can share what I've done. I should also have the rates going back to the start of 2017. We may want to just start saving them with this project so that people that need historical can get it easily.

**Comment by antstorm** [comment]
@zachaysan that's a really interesting point! An offline DB of exchange rates might be quite useful for some projects.

I definitely agree that a good example of how this should be used is worth adding.
