### ISSUE TITLE
Loosen dependency on money gem

### ISSUE THREAD

**Issue by timdiggins** [RubyMoney/eu_central_bank#67]
Currently if you add money to Gemfile and install you'll get `6.10.1`. If you then install eu_central_bank you'll get `0.3.8` (!) -- because this was the last one that had a loose dependency (>= 6.0.1). To get the latest eu_central_bank you need to downgrade money to `6.9.0`. 

I think eu_central_bank should be able to work with 6.x.x (cause breaking changes would surely require a change to 7.x.x). So the dependency on money in gemspec should be 

```
  s.add_dependency "money", "~> 6.9"
```

I hope that sounds reasonable. I'll submit a PR if I can make it all work.

**Comment by antstorm** [comment]
@timdiggins yep, agree, thank you for fixing this!
