### ISSUE TITLE
Missing ISK conversion support

### ISSUE THREAD

**Issue by MathEman-1** [RubyMoney/eu_central_bank#79]
We have a use case where we need to convert ISK to another currency.

I checked the central bank rates that are downloaded by saving the rates locally "eu_bank.save_rates(cache)".

It turns out that the ISK currency is included in the xml, but not supported by the gem. Could you add this as a supported currency?

**Comment by antstorm** [comment]
https://github.com/RubyMoney/eu_central_bank/pull/80

**Comment by antstorm** [comment]
A new version (1.3.0) should now be available with ISK support

**Comment by MathEman-1** [comment]
Thanks for the fast fix!
