### ISSUE TITLE
Update gemspec to support latest nokogiri ?

### ISSUE THREAD

**Issue by mgadikota-rpx** [RubyMoney/eu_central_bank#95]
Currently eu_central_bank is locked to >=1.8.0 and <1.9 is there any reason behind it ? Will it break if we update gemspec to latest or >=1.9 version ? 

**Ruby: 2.5.3
Rails 5.2.2**

**Comment by antstorm** [comment]
I think we're just being a bit cautious around bigger updates. I've merged your PR, will release shortly
